### ISSUE TITLE
Signing Raw-bytes fails to generate correct signature

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/parity-signer#1014] opened 2022-04-26 08:40 UTC
Hi, 
this is an extension (possibly even a duplicate of #997). When I am signing raw bytes with my signer the generated signature is not valid (at least polkadot-js is not able to recognize and verify the signature). 
Usually, every raw-bytes payload (when generated from polkadot-js) is wrapped like `<Bytes>MESSAGE<\Bytes>`. But as you can see in the appended screenshots the payload that signer is signing is `Bytes>Message<\Bytes>`, the leading `<` is missing. 

As signing with keys stored in the polkadot-js-extension works fine, I guess it is a parsing error on the signer side or the qr-code generation on the polkadot-js side is erroneous. 

### Context 
* Signing a message `s` with a key stored in the parity signer
* Signing Account: `13p7q4N8aQqnGJRGnevq8e8k8rsXkF8S7u1E5694XtRviJc`
* Signature from iOS: `0x01f622c83416200a56b7e39fdb52d76e8128eabd3979419cdf2b258c5eb0a323466a5adea9cd2d114d2a203563f87403f68d8ab4b548b3f3d7ae52cfa587adbb8a`
* Signature from Android: `0x01d2c2177fc025135a63155ccf89cda60c76cc5cf7a3c67fbd1af9715e56d9a370d5ec0b05fcf0d26229b5c27b8fa8833cc6ebbf0086823f4c01f0692965f4008a`

* QR-Code generated by polkadot-js
   <img width="565" alt="issue_parity_signer-QR_code" src="https://user-images.githubusercontent.com/28841470/165255932-44adc665-c6cc-476f-9897-87a47c41cb56.png">

As you can see in the screenshots the message to sign is for both devices `Bytes>s<\Bytes>` and polkadot-js is not able to recognize the signature, neither the used crypto. 

#### Android
* Message to sign
   <img width="400" height="600" alt="issue_parity_signer-verification_signature_android" src="https://user-images.githubusercontent.com/28841470/165255862-25a03c7e-a5dd-4a9c-b6ed-171be9e5da2c.png">

* Verification of Signatures
   <img width="1780" alt="issue_parity_signer-verification_signature_android" src="https://user-images.githubusercontent.com/28841470/165254600-e805de01-7e37-4e36-81e1-de1ee06976e3.png">

#### iOS
* Message to sign
   <img width="400" height="600" alt="issue_parity_signer-verification_signature_android" src="https://user-images.githubusercontent.com/28841470/165257838-fce80e2c-67be-4fc9-a291-8e9b7dc9c5bf.png">
* Verification of Signatures
   <img width="1765" alt="issue_parity_signer-verification_signature_iOS" src="https://user-images.githubusercontent.com/28841470/165254630-942aec66-878b-49da-9279-f98e08319f16.png">

### Setup
Tested both on iOS and Android with the same key.
* iOS 15.4.1, Signer v5.0.0
* Android 8.0.0, Signer v5.0.1
* Site used to generate QR-codes: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/signing

**Comment by Slesarew** [comment] 2022-04-26 09:32
Apparently, the QR generator you used does indeed encode verbatim any message you supply - without scale-encoding it. Signing non-scale payloads is not supported. Due to a miraculous coincidence though, `<` symbol exactly matches length of subsequent message, turning non-scale encoded `<Bytes>MESSAGE<\Bytes>` into scale-encoded `Bytes>MESSAGE<\Bytes>` so go buy yourself a lottery ticket (not an investment advice, a joke). This coincidence provides a clue to what really happened.

We should probably fix this on polkadot.js side. This is very likely to be duplicate of #997 indeed and this should be fixed on hot side.

The payload produced by Signer starts with encryption type byte. I think you should crop the `01` part from the start of signature string for it to work if you are using the raw interface.

**Comment by mustermeiszer** [comment] 2022-04-26 10:16
TBH not a really good and nice joke. The "miraculous" coincidence also happens with any arbitrary message I use when signing with parity signer on iOS. I give you that, that it indeed fails on the android version.

**Comment by mustermeiszer** [comment] 2022-04-26 10:19
Just for the sake of completion: 

* For single-digit (u8) message: Signature is VALID when removing leading `01`
* For multi-digit (u8) message: Signature is INVALID when removing leading `01`

**Comment by Slesarew** [comment] 2022-04-26 10:27
Sorry for my sick sense of humor.

The fact that single-digit messages pass agrees well with the `<` being scale-encoded length of `Bytes>*<\Bytes>` only when * is one symbol.

Crash on longer improperly encoded lines is something I should definitely fix.

**Comment by Slesarew** [comment] 2022-04-26 10:30
Wait, it is not a bug, but a feature (added in 5.0.1). Signer should generate an error if not whole payload was parsed, and if there are more symbols then declared it should not sign anything.

**Comment by mustermeiszer** [comment] 2022-04-26 10:31
Sounds fair. What is the reasoning behind signing only scale-encoded values?

**Comment by Slesarew** [comment] 2022-04-26 12:12
I'll mention the extension issue here https://github.com/polkadot-js/extension/issues/1052

> What is the reasoning behind signing only scale-encoded values?

It is impossible to determine whether the payload is scale-encoded or not by its format. The message signing called for scale-encoded format and this is the simplest explanation really.

The target messages format is scale-encoded, by creating ambiguity in interpreting payloads we create potential paths to attack - `<Bytes>` wrapping solves this partially, because in the end it is not really enforced in 3rd party tools (does not have to be) and it is possible to disguise actual malicious payloads as difficult to read messages.

It is also important that scale-encoding allows the whole QR to be parsed exhaustively making sure everything worked as intended and nothing extra is being transferred or encoded.

**Comment by Slesarew** [comment] 2022-05-23 07:29
This should be fixed, as https://github.com/polkadot-js/extension/issues/1052 is closed now. Please confirm.

**Comment by mustermeiszer** [comment] 2022-05-24 09:11
It's not published to the stores, so users will still experience this issue if I am not mistaken.

But signing message, in general, is now impossible with QR codes, which does not exactly solve this issue in my opinion. But I think we can close this. This should be an issue on the extension side rather than on the signer IMO.

**Comment by Slesarew** [comment] 2022-05-24 09:17
Nah, we'll fix it soon on both sides. I think we've come up with some solution in #997 and around.

**Comment by prybalko** [comment] 2022-10-06 12:55
Fixed in #1332

**Closed** 2022-10-06 12:54 UTC
Labels: hot side

**Comment by prybalko** [comment] 2022-10-10 08:34
It has been fixed only on the Signer side (but not yet released). 
https://github.com/polkadot-js/extension/pull/1053 needs to be reverted.

**Comment by Tbaut** [comment] 2022-10-13 11:55
I put up a PR to revert the QR code signing in the extension here https://github.com/polkadot-js/extension/pull/1155
