### ISSUE TITLE
Portal URL is parity.metadata.io instead of metadata.parity.io

### ISSUE THREAD

**Issue by rossbulat** [paritytech/parity-signer#1840] opened 2023-05-21 15:48 UTC
The metadata instructions are displaying the wrong URL.

**Comment by Tbaut** [comment] 2023-05-21 17:39
Duplicate of https://github.com/paritytech/parity-signer/issues/1788

**Closed** 2023-05-21 17:47 UTC

**Comment by rossbulat** [comment] 2023-05-22 07:38
Nice!
