### ISSUE TITLE
"Delete Account" does not work on accounts created with prev version; accounts restored after re-install

### ISSUE THREAD

**Issue by laboon** [paritytech/parity-signer#412] opened 2019-10-10 15:20 UTC
DESCRIPTION
If you delete an account, that account is not really deleted.  If you uninstall and re-install the application, the deleted accounts are available once again.

As a side note, upon reinstall, any name changes you made will be reverted back to the original name.

TO REPRODUCE
1. Delete account TESTACCOUNT 
2. Uninstall Parity Signer
3. Re-install Parity Signer
4. Open Parity Signer

EXPECTED BEHAVIOR
TESTACCOUNT is not in list of accounts

OBSERVED BEHAVIOR
TESTACCOUNT _is_ in list of accounts

NOTES
This was on an iPhone 6 SE (Model Number MP7T2LL/A), software version 12.4.1.

**Comment by laboon** [comment] 2019-10-10 15:28
Looking through my accounts, it looked like it _did_ delete my Kusama accounts, just not my Ethereum ones.

**Comment by laboon** [comment] 2019-10-10 15:28
I just realized that I also generated these on a different version of Parity Signer, which may be relevant.

**Comment by Tbaut** [comment] 2019-10-10 15:32
Right, this is a very tricky case.. a proper Signer usage would prevent that, because you should not update Signer by upgrading the app with having your phone online...

Now I'm less surprised by this. Although we did implement a way to migrate older accounts, you most probably have a borked DB. I could not reproduce with a freshly installed Signer, with Kusama or Ethereum accounts.

**Comment by laboon** [comment] 2019-10-10 15:36
Yes, earlier I had assumed that I could use Parity Signer, delete the application, and simply keep the generated seed on paper.  But I did not realize that deleting the app did not delete its data.

**Comment by laboon** [comment] 2019-10-10 15:36
So I guess this not as big an issue as originally thought as it will not happen to users using the app correctly.

**Comment by Tbaut** [comment] 2019-10-10 15:38
>  But I did not realize that deleting the app did not delete its data

If you delete the app without having deleted the account, an iphone will keep that info (encrypted). Android would flush everything.

On iphone you'de have to delete things manually before uninstalling the app. Our instructions are much more radical though, you should factory reset the phone before setting it online again to download a new Signer version.

**Comment by hanwencheng** [comment] 2019-10-11 13:51
> If you delete an account, that account is not really deleted. If you uninstall and re-install the application, the deleted accounts are available once again.

The seed data on iOS is stored in the keychain. In this case after uninstalling and reinstalling the app, iOS do not have ways to prevent accessing data from same device. 

> As a side note, upon reinstall, any name changes you made will be reverted back to the original name.

The normal database of the application is flushed, so the generated data like `seed <=> name` mapping is gone. It is an expected behavior.

The first problem could to be solved, either:
* Delete the keychain related data (e.g. `account_v3` in current version) each time on iOS deleted. (with native iOS code).
* create `deleteAllItems` function in `react-native-secure-storage`. We offer users a function for clear all the account data, and ask them to do that before uninstalling (User have the perception that all data is deleted). Or call this function on the application's first launch.

**Comment by Tbaut** [comment] 2019-10-12 07:24
We shouldn't try to work around a bug
If the original bug "can't delete an account that has been migrated" wasn't present, we wouldn't need any of what's suggested. My recent PR could also very much help with this because it aligns the way we store things in the keychain and the local storage (memory).

**Comment by Slesarew** [comment] 2021-08-25 12:56
fixed in #791

**Closed by Slesarew** 2021-08-25 12:56 UTC
Labels: P9-somedaymaybe
