### ISSUE TITLE
Signing transaction does not work

### ISSUE THREAD

**Issue by debris** [paritytech/parity-signer#129] opened 2018-08-06 12:09 UTC
transaction from README.md -> https://github.com/paritytech/parity-signer/blob/8b4e3575973b1abfc73ce0c4d07717cb47e1bcd5/README.md#example

**Comment by fckt** [comment] 2018-08-06 12:47
the problem is that the transaction have no specified chainId.. Looks like it should fallback to the default one.

**Comment by fckt** [comment] 2018-08-06 14:33
Btw, which error message you've got?

**Comment by debris** [comment] 2018-08-07 13:06
I wanted to reproduce it, but I stumbled upon #130

**Comment by fckt** [comment] 2018-08-17 14:29
Let's close it for now. Will reopen it, if the issue arise again.

**Comment by debris** [comment] 2018-08-20 08:40
![photo_2018-08-20_10-37-57](https://user-images.githubusercontent.com/2613714/44329653-44ef8480-a465-11e8-8469-7a6188743f0c.jpg)
![photo_2018-08-20_10-37-51](https://user-images.githubusercontent.com/2613714/44329654-44ef8480-a465-11e8-9bb1-b82b1d11933a.jpg)

I just reproduced it again with the latest build. Please do not close the issues. Make a pull request with the reference to the issue being fixed.

**Comment by fckt** [comment] 2018-10-15 06:58
@debris looks like this has been fixed

**Closed by fckt** 2018-10-15 06:58 UTC
Labels: F2-bug
