### ISSUE TITLE
When a new network is added, current key set don't show the address for it

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#1787] opened 2023-04-17 22:16 UTC
How to reproduce:
- create an account (key set, BTW this name sounds really weird to me and isn't used anywhere in the ecosystem)
- see the address for Kusama, Polkadot, Westend

- Now add a new Network, say Astar (with spec and metadata)
- Go see the account from the 1st step, it's not showing Astar :(

If you create a new key set, Astar address will be displayed.

What I would expect:
I would like to see the address for accounts that were created/added to Vault prior to adding the network.

**Comment by krodak** [comment] 2023-04-17 22:49
@tetekinandrey would that be expected behavior currently?

**Comment by montekki** [comment] 2023-04-19 14:31
Yeah that has never worked since adding that automatically would require going to secure enclave for the seed => unlock the device. In fact I would advocate not adding _any_ accounts automatically (also when generating a seed)

**Comment by Tbaut** [comment] 2023-04-19 17:56
Right, it should be all or nothing. And more importantly it should be possible to add a network later, and without derivation path.

**Comment by tetekinandrey** [comment] 2023-04-20 04:36
I can see two ways of communicating this to users:

– When adding a new network ask users if they'd want to add a root key for the new network. Add a key instantly if they want.
– When a new key set is created ask users on what networks they'd to create root keys. If no networks are added to the app besides DOT, KSM, WND, don't ask for anything. If new networks are chosen, add keys instantly.

**Comment by prybalko** [comment] 2023-07-14 10:25
Fixed in:
ios: https://github.com/paritytech/parity-signer/pull/1901
android: https://github.com/paritytech/parity-signer/pull/1902

**Closed by prybalko** 2023-07-14 10:25 UTC
Labels: backend
