### ISSUE TITLE
App crashes when wrong 'current PIN' is entered in change PIN view

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity-signer#72] opened 2017-07-23 23:51 UTC

**Comment by debris** [comment] 2017-07-26 12:18
cannot reproduce :( are you sure you have the latest version?

**Comment by debris** [comment] 2017-07-26 12:18
can you check it with newly created account?

**Comment by debris** [comment] 2017-07-31 13:49
fixed in ff9294b724a3b0ceebf51ba600493a99e620dba9

**Closed** 2017-07-31 13:49 UTC
