### ISSUE TITLE
[v4.6.4] Can't update network metadata for Westend

### ISSUE THREAD

**Issue by skowa85** [paritytech/parity-signer#882] opened 2021-11-22 14:57 UTC
I'm using the internal testing version 4.6.4.

When trying to update the network metadata for Westend (9111 -> 9122) via scanning the QR code on polkadot.js.org apps, I receive the following error:

> Error! Only Substrate transactions are supported. Transaction is expected to start with 0x53.

**Comment by Slesarew** [comment] 2021-11-22 17:15
This is intended behavior. The metadata on polkadot.js is not signed and is thus not safe to use. Furthermore, it has legacy format and also that QR does not actually contain any metadata. You should either generate update using `rust/generate_message` crate in this repository or find metadata update portal; the only one is available internally in notion under "signer experience" space.

This is duplicate of something, yes, we desperately need cleaner instructions and public metadata update portal.

**Closed by Slesarew** 2021-11-22 17:15 UTC
