### ISSUE TITLE
android: QR parsing is slow

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#1762] opened 2023-03-31 08:36 UTC
QR parsing on Android is extremely slow. 

Here is a video comparing Pixel 4a with iPod touch:

https://user-images.githubusercontent.com/7165377/229068965-4bb118db-c1e7-4a46-9f27-05b3feed5d0f.MOV

**Comment by Tbaut** [comment] 2023-03-31 08:42
I have installed one of last week's master version on a Pixel 3a and was surprised how slow it was compared to before (version 5). I meant to test on a hot device to see if there was a noticeable change but this issue confirm this. I certainly remember needing less than a minute for 300+ frames. Now it's much more.

**Comment by Zerophase** [comment] 2023-03-31 08:47
Also happens with PIxel 4a (5g). Don't believe it scans anything. The screen turns off before the scan finishes.

**Comment by Dmitry-Borodin** [comment] 2023-03-31 16:57
Thank you for contribution. Please follow up in existing issue for this topic #1436
Framing changed in last/this week, please let us know if it still much slower than was before. You can check on master on recently released version.

**Comment by Zerophase** [comment] 2023-03-31 19:16
Last release I see was from almost a year ago. Are we close to having a new release?

**Comment by Tbaut** [comment] 2023-04-01 23:05
@Dmitry-Borodin I've tried with the latest build to date from maste, the frame position isn't the problem. I'm comparing v5 and v6, the difference is like day and night. On a pixel 4a, it's at least 2 or 3 times faster on v5. I changed my signer device because on v5 my old phone was too slow. Now I feel like I'm back to square one unfortunately.

The v6 camera is zoomed where the v5 is not, maybe that's something to take a look at, where zooming is loosing in resolution?

**Comment by Dmitry-Borodin** [comment] 2023-04-03 18:27
@Zerophase it was released end of last week.

@Tbaut Yes, you are right, it is zoomed because with new UI we need to show camera data for full screen vertically, it is done by cropping a lot from original camera image (mostly from sides).
Barcode scanner component scanning original images from camera and doesn't support only selected image at the moment.
I'm thinking of implementing it with manual cropping images before processing if other solution won't be found. But it's not the case at the moment.
Could you check if zooming in QR code on a screen helps? I've reproduced decrease of QR recognition performance (still usable through) when I open portal in small screen of my laptop and under weak light conditions. And it is solved by increasing browser scale to make QR code on a screen bigger, so I can keep device more far away from computer screen.

So 2 simple ways to check if you mind:
 - zooming in qr code on computer by browser scale.
 - moving your phone closer - we recognizing camera data, not only things you can see on a screen, cropped (I think almost all on a sides) part is participated in recognition as well.

**Comment by prybalko** [comment] 2023-04-03 19:19
Moving phone closer to the image does increase performance.

> it is zoomed because with new UI we need to show camera data for full screen vertically.

This is problematic. I'd suggest implementing it like in the iOS app, i.e. uncropped image, non-transparent borders

**Comment by krodak** [comment] 2023-04-03 20:49
> Moving phone closer to the image does increase performance.
> 
> > it is zoomed because with new UI we need to show camera data for full screen vertically.
> 
> This is problematic. I'd suggest implementing it like in the iOS app, i.e. uncropped image, non-transparent borders

Just for the clarity, iOS shows camera preview on whole screen, not just the cutout - but QR code detection is simply not limited to cut out itself, to not limit performance of scanning operation, I think it’s sensible compromise between UX enforced by UI and pure performance

**Comment by Zerophase** [comment] 2023-04-04 09:14
> @Zerophase it was released end of last week.

Going to package a Github release?

**Comment by Dmitry-Borodin** [comment] 2023-04-04 16:01
@Tbaut  would be really great to hear your feedback if this fixes your problem as well #1764

**Comment by Dmitry-Borodin** [comment] 2023-04-05 15:58
related to #1436 


@Tbaut Thanks for your input.
I agree.

**Comment by Dmitry-Borodin** [comment] 2023-04-14 20:50
This huge performance degradation was fixed above and available in current released version.
Future improvements in qr recognition will be happening within #1436
I will close this one as duplicated.

**Closed by Dmitry-Borodin** 2023-04-14 20:50 UTC
Labels: android
