### ISSUE TITLE
Seed phrase issue (Polkadot Centrifuge)

### ISSUE THREAD

**Issue by vacoolaaa** [paritytech/parity-signer#927] opened 2022-02-14 15:05 UTC
Hi all. I'm trying to get the seed phrase from my iPhone, but instead of the phrase, I see a set of wallets and paths.
How can I get a seed phrase from this?
![parity2](https://user-images.githubusercontent.com/31446918/153889213-58e77871-efd0-4a92-8edd-efced4dbff38.jpg)

**Comment by Slesarew** [comment] 2022-02-14 17:28
This is caused by installing Signer on top of previously installed version of Signer. Due to airgapped nature of the app, this is not supported and Signer will erase data prom prior versions in upcoming releases (pretty soon just to nail this surprisingly popular issue).

To use this Signer, please go to settings and click "wipe" button.
To recover old seeds, install older version of the app (same one you used before), backup seeds to paper, then wipe the phone and install new Signer.

**Comment by vacoolaaa** [comment] 2022-02-14 17:59
Thank you, but how can I install the previous version of the app on the iPhone?

**Comment by Slesarew** [comment] 2022-02-14 18:29
Looks like you'll have to switch to tagged release and build it. There are numerous manuals on the internet on how to downgrade - but essentially they all potentially breach airgap defying the whole purpose of the Signer security.

If you have paper backup of the seed (as you should at all times, Signer is not a seed storage device, seed should always be backed up), you should use it now.

If you don't, the safest approach would actually be to copy the text from the screen, one of the fields contains encrypted seed. Fortunately (in this particular case, unfortunately otherwise), the older versions of Signer did not use hardware backing of storage, thus the password used for encryption is just your pin code used for this seed in older version of Signer. Here is how encryption was done IIRC: https://github.com/paritytech/parity-signer/blob/9e8d654a7301a4520ad6c7c41d77446a49125eba/rust/signer/src/lib.rs#L179, please use that code as reference to decode.

**Comment by Slesarew** [comment] 2022-02-14 20:44
Perfect! Now that we don't have to worry about seed phrase recovery, to adding Centrifuge.

To use networks other than default set, you should add these networks and their up-to-date metadata to Signer via airgapped QR updates. This is mandatory because with newer Substrate functionality blind signing is worse than not having an airgap from security point of view. To add a network, you could either use one of "centralized" update distribution services (as far as I know, the only public one is [reference metadata portal](https://metadata.parity.io/) and it does not support Centrifuge at this moment) or generate an update yourself using [this crate](https://github.com/paritytech/parity-signer/tree/master/rust/generate_message) (see usage examples); this could not be done automatically yet for security reasons.

Now, there is another problem. Last I checked, Centrifuge had an outdated metadata version incompatible with Signer (including non-standard types that have to be hard-coded into types definitions). If that is still the case, then Centrifuge is unusable in Signer 5.0.0 until their maintainers update.

My suggestion is - if metadata could not be sent over an airgap, signing transactions with Signer is less safe in most cases than signing them using non-airgapped solutions. You can re-generate your key on a trusted computer using [subkey](https://github.com/paritytech/substrate/tree/master/bin/utils/subkey) tool or import it from seedphrase in polkadot.js or any of other compatible tools; until Centrifuge gets upgraded, it is not compatible with Signer, or, in other words, using it with proper airgapped tool would degrade security at the moment due to inability to keep transaction parser up to date in reasonable manner.

**Comment by Slesarew** [comment] 2022-02-15 06:47
> Account Format Transform doesn't work also, it shows me a different address from the original.

If this is the case, then you are probably using wrong [derivation path](https://docs.substrate.io/v3/tools/subkey/#hd-key-derivation). Default paths are usually `//networkname`.

**Comment by Slesarew** [comment] 2022-02-15 12:53
I will close this as duplicate of several related issues, while creating a separate issue for one that's new here: https://github.com/paritytech/parity-signer/issues/928.

**Closed by Slesarew** 2022-02-15 12:53 UTC
