### ISSUE TITLE
Hide "confirm password" modal when key creation collision happens on non-matching paths

### ISSUE THREAD

**Issue by Slesarew** [paritytech/parity-signer#1019] opened 2022-04-27 09:02 UTC
Reproducing:

1. Create key `//1///1`
2. Create key `//01///1`

**Comment by krodak** [comment] 2023-03-23 11:37
Fixed with updated UX flow for that, couldn't reproduce, closing for now.

**Closed by krodak** 2023-03-23 11:37 UTC
Labels: backend, UX
